export const slides = [
  {
    src: "/team/max/founders.jpg",
    thumbnail: "/team/founders.jpg",
    mini: "/team/min/founders.jpg",
    description: "Gründerinnen Anna Ableidinger & Bettina Beneda",
    horizontal: false,
  },
  {
    src: "/team/max/fairies.jpg",
    thumbnail: "/team/fairies.jpg",
    mini: "/team/min/fairies.jpg",
    description: "Fairies",
    horizontal: false,
  },
  {
    src: "/team/max/fireflies.jpg",
    thumbnail: "/team/fireflies.jpg",
    mini: "/team/min/fireflies.jpg",
    description: "Fireflies",
    horizontal: true,
  },
  {
    src: "/team/max/firebirds.jpg",
    thumbnail: "/team/firebirds.jpg",
    mini: "/team/min/firebirds.jpg",
    description: "Firebirds",
    horizontal: true,
  },
  {
    src: "/team/max/all-level.jpg",
    thumbnail: "/team/all-level.jpg",
    mini: "/team/min/all-level.jpg",
    description: `Meisterschaft "All-Level"`,
    horizontal: false,
  },
  {
    src: "/team/max/united-cheer-cup.jpg",
    thumbnail: "/team/united-cheer-cup.jpg",
    mini: "/team/min/united-cheer-cup.jpg",
    description: "United Cheer Cup '25",
    horizontal: true,
  },
  {
    src: "/team/max/screaming-anna.jpg",
    thumbnail: "/team/screaming-anna.jpg",
    mini: "/team/min/screaming-anna.jpg",
    horizontal: true,
  },
];
