export const slides = [
  {
    src: "/team/max/founders.jpg",
    thumbnail: "/team/founders.jpg",
    mini: "/team/min/founders.jpg",
    key: "founders",
    horizontal: false,
  },
  {
    src: "/team/max/fairies.jpg",
    thumbnail: "/team/fairies.jpg",
    mini: "/team/min/fairies.jpg",
    key: "fairies",
    horizontal: false,
  },
  {
    src: "/team/max/fireflies.jpg",
    thumbnail: "/team/fireflies.jpg",
    mini: "/team/min/fireflies.jpg",
    key: "fireflies",
    horizontal: true,
  },
  {
    src: "/team/max/firebirds.jpg",
    thumbnail: "/team/firebirds.jpg",
    mini: "/team/min/firebirds.jpg",
    key: "firebirds",
    horizontal: true,
  },
  {
    src: "/team/max/all-level.jpg",
    thumbnail: "/team/all-level.jpg",
    mini: "/team/min/all-level.jpg",
    key: "all-level",
    horizontal: false,
  },
  {
    src: "/team/max/united-cheer-cup.jpg",
    thumbnail: "/team/united-cheer-cup.jpg",
    mini: "/team/min/united-cheer-cup.jpg",
    key: "united-cheer-cup",
    horizontal: true,
  },
  {
    src: "/team/max/screaming-anna.jpg",
    thumbnail: "/team/screaming-anna.jpg",
    mini: "/team/min/screaming-anna.jpg",
    key: "screaming-anna",
    horizontal: true,
  },
];
